/**
 * Regenerates src/lib/ascii-data.ts: the precomputed ASCII divider strips.
 * Run with `pnpm gen:ascii` after changing renderDivider or the seeds.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { renderDivider } from "../src/lib/ascii.ts";

const SEEDS = [1984, 2027] as const;
const ROWS = 3;
// 7px Geist Mono advances 4.2px, so 640 columns covers a 2688px-wide viewport.
const COLS = 640;

// Numeric keys, unquoted, so `keyof typeof DIVIDERS` is 1984 | 2027.
const body = SEEDS.map((seed) => {
  const rows = renderDivider(seed, ROWS, COLS)
    .map((row) => `    ${JSON.stringify(row)},`)
    .join("\n");
  return `  ${seed}: [\n${rows}\n  ],`;
}).join("\n");

const out = `// Generated by scripts/gen-ascii.ts. Do not edit by hand.
// ${ROWS} rows x ${COLS} columns per divider.

export const DIVIDERS = {
${body}
} as const satisfies Record<number, readonly string[]>;

export type DividerSeed = keyof typeof DIVIDERS;
`;

const target = fileURLToPath(new URL("../src/lib/ascii-data.ts", import.meta.url));
writeFileSync(target, out);
console.log(`Wrote ${SEEDS.length} dividers to ${target}`);
